### ISSUE TITLE
Exception at Invalid load

### ISSUE THREAD

**Issue by JavaK32** [SHIELD-DevTeam/shield-compiler#7]
java.io.FileNotFoundException: Test000.shieldproject (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at java.base/java.io.FileReader.<init>(FileReader.java:75)
        at StreamFileReader.read(StreamFileReader.java:49)
        at ProjectConfigaration.<init>(ProjectConfigaration.java:74)
        at ShieldSwitch.loadProject(ShieldSwitch.java:178)
        at ShieldSwitch.switchProcess(ShieldSwitch.java:58)
        at Main.main(Main.java:43)
Exception in thread "main" java.lang.NullPointerException
        at ShieldSwitch.multiReplace(ShieldSwitch.java:197)
        at ProjectConfigaration.getProjectRoot(ProjectConfigaration.java:87)
        at ShieldSwitch.loadProject(ShieldSwitch.java:178)
        at ShieldSwitch.switchProcess(ShieldSwitch.java:58)
        at Main.main(Main.java:43)

**Comment by JavaK32** [comment]
java.io.FileNotFoundException: H.shieldproject (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at java.base/java.io.FileReader.<init>(FileReader.java:75)
        at StreamFileReader.read(StreamFileReader.java:49)
        at ProjectConfigaration.<init>(ProjectConfigaration.java:75)
        at ShieldSwitch.loadProject(ShieldSwitch.java:181)
        at ShieldSwitch.switchProcess(ShieldSwitch.java:60)
        at Main.main(Main.java:43)
java.io.FileNotFoundException: H.shieldproject (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at java.base/java.io.FileReader.<init>(FileReader.java:75)
        at StreamFileReader.read(StreamFileReader.java:49)
        at ProjectConfigaration.<init>(ProjectConfigaration.java:75)
        at ShieldSwitch.loadProject(ShieldSwitch.java:183)
        at ShieldSwitch.switchProcess(ShieldSwitch.java:60)
        at Main.main(Main.java:43)
Exception in thread "main" java.lang.NullPointerException
        at ShieldSwitch.multiReplace(ShieldSwitch.java:204)
        at ProjectConfigaration.getProjectRoot(ProjectConfigaration.java:88)
        at ShieldSwitch.loadProject(ShieldSwitch.java:183)
        at ShieldSwitch.switchProcess(ShieldSwitch.java:60)
        at Main.main(Main.java:43)

**Comment by JavaK32** [comment]
Project Does not exist
java.io.FileNotFoundException: H.shieldproject (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at java.base/java.io.FileReader.<init>(FileReader.java:75)
        at StreamFileReader.read(StreamFileReader.java:49)
        at ProjectConfigaration.<init>(ProjectConfigaration.java:78)
        at ShieldSwitch.loadProject(ShieldSwitch.java:181)
        at ShieldSwitch.switchProcess(ShieldSwitch.java:60)
        at Main.main(Main.java:43)
Exception in thread "main" java.lang.NullPointerException
        at ShieldSwitch.multiReplace(ShieldSwitch.java:203)
        at ProjectConfigaration.getProjectRoot(ProjectConfigaration.java:91)
        at ShieldSwitch.loadProject(ShieldSwitch.java:181)
        at ShieldSwitch.switchProcess(ShieldSwitch.java:60)
        at Main.main(Main.java:43)
